title: Doris Lyuâ€˜s Portfolio # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  There is Doris Lyu's Portfolio showcasing my works from my wed design class. 
  <br><br>
  Please contact me if you would like me to create a wecsite for you or your company.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
